name: Build

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  # === HTML ===
  html:
    runs-on: ubuntu-latest

    steps:
      - uses: mymindstorm/setup-emsdk@v14
        with:
            version: 3.1.51

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build
        run: |
          cd build
          emcmake cmake -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_STUB=On ..
          cmake --build . --config $BUILD_TYPE --parallel
          cp html/index.html bin/index.html

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: "tic80-html"
          path: |
            build/bin/tic80.js
            build/bin/tic80.wasm
            build/bin/index.html

  # === Export ===
  export:
    needs: [html]
    runs-on: ubuntu-latest

    steps:
      - name: Download HTML artifact
        uses: actions/download-artifact@v3
        with:
          name: tic80-html

      - name: Rename
        run: |
          zip html.zip index.html tic80.js tic80.wasm
          mv -f html.zip html

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: "tic80-export"
          path: |
            html
