name: Build

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  # === HTML ===
  html:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gameon'

    steps:
      - uses: mymindstorm/setup-emsdk@v14
        with:
            version: 3.1.51

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build
        run: |
          cd build
          emcmake cmake -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_STUB=On ..
          cmake --build . --config $BUILD_TYPE --parallel
          cp html/index.html bin/index.html

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-gameon"
          path: |
            build/bin/tic80.js
            build/bin/tic80.wasm
            build/bin/index.html
